In [63]:
# Quiz # 1 
# Student: Jose Martinez Hdez
# Course: Data Science 
# Year: 2021

import torch

def matrix_propierty_1(A):
  # Sanity check 
  if len(A) != len(A[0]):
    print("Matrix isn´t nxn")
    return False
  if torch.det(A) == torch.tensor(0):
    print("Matrix isn´t invertible")
    return False

  # Local variables 
  A_inv = torch.inverse(A)
  A_t = torch.transpose(A, 0, 1)
  A_inv_t = torch.transpose(A_inv, 0, 1)
  
  # Calculate left side 
  left = torch.mm(A_inv_t, A_t)
  print("-> left side:\n{}".format(left))

  # Calculate right side 
  right = torch.mm(A_t, A_inv_t)
  print("-> right side:\n{}".format(right))

  # Calculate and print ¨left-right¨ 
  M = torch.add(left, -right)
  print("-> left side - right side:\n{}".format(M))

  # Compare all values of the matrix and take into account 
  # small precision differences
  return torch.all(torch.lt(torch.abs(M), 1e-6))

# Create random matrix 
A = torch.randn(3,3)

# Demostrate whether the equation is true or not 
print("Is the equation true? \n- Answer: {}".format(matrix_propierty_1(A)))

-> left side:
tensor([[ 1.0000e+00, -3.1815e-08,  8.8399e-08],
        [-5.7526e-08,  1.0000e+00, -7.6765e-08],
        [-1.1423e-07, -2.6550e-08,  1.0000e+00]])
-> right side:
tensor([[ 1.0000e+00, -1.3467e-07,  7.1074e-08],
        [-4.2958e-08,  1.0000e+00,  1.2113e-08],
        [ 2.1729e-08,  4.0547e-08,  1.0000e+00]])
-> left side - right side:
tensor([[ 1.1921e-07,  1.0285e-07,  1.7325e-08],
        [-1.4568e-08,  5.9605e-08, -8.8878e-08],
        [-1.3596e-07, -6.7096e-08,  2.9802e-07]])
Is the equation true? 
- Answer: True


Se tiene que:

$$\left(A^{-1}\right)^{T}A^{T}=A^{T}\left(A^{-1}\right)^{T}$$

  Donde $A\in\mathbb{R}^{n\times n}$ invertible. Resolviendo la ecuación anterior del lado izquierdo y por propiedades de la traspuesta se llega a:

$$\left(A^{-1}A\right)^{T}=A^{T}\left(A^{-1}\right)^{T}$$

Al $A$ ser una matriz invertible, cumple con la definición de:

$$A^{-1}A = I = AA^{-1}$$

Sustituyendo la ecuación anterior en el lado izquierdo, se llega a:

$$\left(AA^{-1}\right)^{T}=A^{T}\left(A^{-1}\right)^{T}$$

Aplicando las propiedades de la traspuesta del lado izquierdo se llega a:

$$A^{T}\left(A^{-1}\right)^{T} = A^{T}\left(A^{-1}\right)^{T}$$ 

In [71]:
import torch

def matrix_propierty_2(A, B):
  # Sanity check
  if len(A) != len(A[0]):
    print("Matrix isn´t nxn")
    return False
  if len(A) != len(B):
    print("Matrix A and B aren't same size")
    return False

  # Calculate left side 
  left1 = torch.add(A, B)
  left2 = torch.add(A, -B)
  left = torch.mm(left1, left2)
  print("-> left side:\n{}".format(left))

  # Calculate right side 
  right1 = torch.mm(A, A)
  right2 = torch.mm(B, B)
  right = torch.add(right1, -right2)
  print("-> right side:\n{}".format(right))

  # Calculate and print ¨left-right¨ 
  M = torch.add(left, -right)
  print("-> left side - right side:\n{}".format(M))

  # Compare all values of the matrix and take into account 
  # small precision differences
  return torch.all(torch.lt(torch.abs(M), 1e-6))

# Create random matrix 
A = torch.randn(3,3)
B = torch.randn(3,3)

# Demostrate whether the equation is true or not 
print("Is the equation true? \n- Answer: {}".format(matrix_propierty_2(A, B)))

-> left side:
tensor([[-0.9539,  1.5318,  1.0293],
        [-1.2858,  0.5348,  1.9227],
        [ 2.8820,  6.9321, -7.0383]])
-> right side:
tensor([[ 0.5502, -0.9434,  1.0111],
        [-3.7144, -1.0677, -1.6537],
        [-3.0018,  3.6157, -6.9400]])
-> left side - right side:
tensor([[-1.5041,  2.4753,  0.0182],
        [ 2.4286,  1.6024,  3.5764],
        [ 5.8838,  3.3164, -0.0983]])
Is the equation true? 
- Answer: False


Se tiene que:

$$\left(A+B\right)\left(A-B\right)=A^{2}-B^{2}$$

Al resolver del lado izquierdo se llega a:
$$ AA - AB + BA + BB =A^{2}-B^{2} $$

Por propiedades de la potencia en matrices:
$$ A^2 - AB + BA + B^2 =A^{2}-B^{2}$$

Pero se sabe que $AB \neq BA$, por lo que dicha propiedad es **falsa**. 